# Generated by Django 5.1.2 on 2024-10-29 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_therapistprofile_experience_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='therapistprofile',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
