# Generated by Django 5.1.2 on 2024-11-03 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_therapistprofile_bio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistprofile',
            name='bio',
            field=models.CharField(blank=True, max_length=600, null=True),
        ),
    ]
