# Generated by Django 5.1.2 on 2024-11-30 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_therapistavailability_day_of_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='therapistavailability',
            name='end_time',
            field=models.TimeField(blank=True),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='is_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='therapistavailability',
            name='start_time',
            field=models.TimeField(blank=True),
        ),
    ]
