# Generated by Django 5.1.2 on 2024-12-11 23:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_therapistavailability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientprofile',
            name='selected_therapist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to=settings.AUTH_USER_MODEL),
        ),
    ]
